TrajectoryPlannerROS:
  max_vel_x: 0.3 
  min_vel_x: 0.2
  min_vel_theta: -1.1
  max_vel_theta: 1.1
  min_in_place_vel_theta: 0.0

  acc_lim_theta: 0.4 #0.78
  acc_lim_x: 1.0 #1.55
  acc_lim_y: 0.0
 
  holonomic_robot: false

  sim_time: 1.7
  sim_granularity: 0.025
 
  oscillation_reset_dist: 0.05
  meter_scoring: true
