global_costmap:
  global_frame: /map
  robot_base_frame: /base_footprint
  update_frequency: 5.0
  static_map: true
  rolling_window: true 
  transform_tolerance: 10
  width: 50.0
  height: 50.0
  resolution: 0.05
  origin_x: 0
  origin_y: 0
