local_costmap:
  global_frame: /odom
  robot_base_frame: /base_footprint
  update_frequency: 5
  publish_frequency: 2
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  origin_x: -3
  origin_y: -3
  transform_tolerance: 10
  circumscribed_radius: 1 # usado en los comportamientos de recuperacion para limpiar costmaps
 
  observation_sources: point_cloud_sensor point_cloud_sensor2
  point_cloud_sensor: {sensor_frame: base_zed, data_type: PointCloud2, topic: /obstacles_cloud, marking: true, clearing: true, min_obstacle_height: 0.25, max_obstacle_height: 1.0} 
  point_cloud_sensor2: {sensor_frame: base_zed, data_type: PointCloud2, topic: /ground_cloud, marking: false, clearing: true, min_obstacle_height: -99999, max_obstacle_height: 99999} 


