@startuml Diagrama de estados del robot

' title Diagrama de estados del robot

storage Enabled#Green
storage Disabled#Crimson
storage Warning#f19300

Enabled --> Warning#f19300 : * alerta de proximidad\n* alerta de velocidad
Enabled --> Disabled : * alerta de proximidad crítica\n* alerta de velocidad crítica\n* alerta de perdida de conexión\n* se recibe comnado para deshabilitar\nal robot desde la SBC
Disabled --> Enabled#Green : * se recibe comando desde SBC \npara habilitar el robot y no hay alertas
Warning  --> Enabled#Green : * cancelación de todas las alertas
Warning  --> Disabled : * aumento de criticidad en alguna alertas
Enabled --> Enabled#Green : * no hay alertas
Warning --> Warning#f193a00 : * hay alertas, ninguna crítica
Disabled --> Disabled : * hay alertas críticas


@enduml

/'
URL Diagram: 
    ![DM3_States](http://www.plantuml.com/plantuml/svg/TL91JWCn3Bpd5PPwG49KAk841rJHLZo00vTUl8bPB6MToabH-oXEFA4V8zbkbrrWRz6CFHwFium9DUqRRymL94wUOCrOApO8Ze0oxKBCJmyQgf2CYIaerWGRmSgJcpqhaVJeckCPNYatCVmGhwZ2Ki_URk_l5WjZkdQOpnz_SV00ru2UDBKMTXeEtB13jvKX_a4-s0AFf2xp9qN0wkapiSK9jGb-H-eoNPus21tuz2Mb8X8eMQuAt4ZE2dQefIo-OyMUSxfRmIwy0cS1Z_3oj3AzrU9xb6PhVgICafNFtRaLjj9EwKV0vJnm10aPFtRMe-coXOaf5iMIHrlsASkbu31cX_5_WN6y-uOaXJOJvPnPcryMHb_l1Nk5uNt-EfZmE_4l1gKtKCWow7AoSQGZhuE-lZmQOvOaBl_-Rm00 "DM3_States")
'/