@startuml Diagrama_de_estados_del_robot

' title Diagrama de estados del robot

storage Enabled#Green
storage Disabled#Crimson
storage Warning#f19300

Enabled --> Warning#f19300 : * alerta de proximidad\n* alerta de velocidad
Enabled --> Disabled : * alerta de proximidad crítica\n* alerta de velocidad crítica\n* alerta de perdida de conexión\n* se recibe comnado para deshabilitar\nal robot desde la SBC
Disabled --> Enabled#Green : * se recibe comando desde SBC \npara habilitar el robot y no hay alertas
Warning  --> Enabled#Green : * cancelación de todas las alertas
Warning  --> Disabled : * aumento de criticidad en alguna alertas
Enabled --> Enabled#Green : * no hay alertas
Warning --> Warning#f193a00 : * hay alertas, ninguna crítica
Disabled --> Disabled : * hay alertas críticas
. -> Disabled#Black : estado inicial

@enduml

/'
URL Diagram: 
    ![Diagrama de estados del robot](http://www.plantuml.com/plantuml/svg/XLD1JiCm4Bpx5IlrW8GeAk841rIrHJo00vTSDlOIB9nrPRkeVHGddj2FiKxIa1GYRjRixEpis5x6X27jQWSRYrN06i4GaA36Hpaw2BxqIQaBI3Ov-eyMamzO4JmobexCx2aGSOzkR6pXTR1rz3-55mnikPgztjpTBXPATUqmdp-SrU0UBW4TXTHOs0Q_jxKrQ0eUuX_alCxmIEeqVr84T3X-9gjnGcsYlgLWf9oFsZFjxV6BCoCI1DAsp73DaXLiCMHQVCFIEYlP5unTU1aM0OVml5ghtchsFKgpCJzIHXRbjbjQeU1cIZy2JjS31s0l-A6p7bMNBKnCqSYQ7EgyJrukUODH7CQ_1SRnxchYv9jCWfNCcln465srO-mLXlVpsy64t_DtWTt3672l85VpfDETZJCTcHtqzVIehc70cwqaY7TXjwyUBCjAw9HQ4XlvGDy0 "Diagrama de estados del robot")
'/