@startuml Diagrama_de_flujo_Dm3Security_Speeds
skinparam activity {
    BackgroundColor MintCream
    BorderColor Peru
    FontName Verdana
}

skinparam note {
    BackgroundColor HoneyDew
    FontName Verdana
    BorderColor Peru
}

start
:start thread;
while(while true)

:obtener reporte de velocidades\ndesde MotorModule;
:filtrar señal;
note left
    Es útil para filtrar errores
    en los sensores de Hall que
    reportan las velocidades angulares
    en las ruedas.
end note
if(la velocidad supera\nla máxima permitida?) then (SI)
    #Tomato:se genera una alerta de\nseguridad con criticidad\nalta indicando el peligro;
else (NO)
    #LightGreen:se genera un alerta de seguridadd\nindicando que las velocidades están\nbajo los parámetros establecidos;
endif
:se envía el alerta generada mediante\nun callback al componente Dm3Security\npara que procese la información y tome\nlas acciones correspondientes;
:esperar 100ms;
endwhile
stop
@enduml

' SVG URL: ![Diagrama_de_flujo_Dm3Security_Speeds](http://www.plantuml.com/plantuml/svg/TLF1RXCn4BtxAqRYabnG4RVaG4KB58aKf29EaQB9UfAwjMUMiRUbGdnCFu03uiPrVwnZfz0WoXwyyipulJVFuyDSKCkG8Xm7t2ecN7bQRU9m8QlZzFoCka53kLcTzKG-ktmPk4Sh0-nAkB8CV7LWtqliBhSg0_iZYQAm25oEb33jigAUT9VvG3gqu6lXSeg9u1EfHqRtpUtXinJw3_Q9CDqSq_NZA8_oLUZQg9kr7vHpq-RdxleyH9gq5OeED7Lk9kj2J0fAlQY9y0HN5AKB7Ztb9TjYeOKKqONu8TBSpJOX5aM5JECFZ7FNr4VQb2RdLORnLmaHQclmkvPKHIct2cA8akquvnghd2SO8tmUgELtMj2gCE-h0UJj474VnWgi4O_vgIFspKSNDfE83-SW3pqfBjc2QRpz4XA21L8ebdqnDNSCQ7BsTjf0dtoKX4LccM1RZK4O604ZcI0JkkHCMnkIYji9GsVp4XhDaZ5QIM0VEcGlGEO0nM1tENSK3Mzo-lwUurtOdfStIiH_yJpGm1yMmts0D8F-yOHo6MzvoMkya6QhsJxU9YegBOdhI5OhULuT2XjNAOclnkzO9TvJxZHuSuXyG2xMgEdfx5RMDezMPTsctaRHKh3tL9PjW9kmNgMZN0MQ2HlHX5qOVpBSG954rNwxmAuB1f8DJUqQ3T272cdYPhQbEYdF3WxIJcoRL1jbwTsXRUtTtW40 "Diagrama_de_flujo_Dm3Security_Speeds")