@startuml Diagrama_de_flujo_Dm3Security_Pows
skinparam activity {
    BackgroundColor MintCream
    BorderColor Peru
    FontName Verdana
}
skinparam note {
    BackgroundColor HoneyDew
    FontName Verdana
    BorderColor Peru
}
start
:start thread;
while(while true)

:obtener reporte de potencias\ny velocidades desde MotorModule;
:filtrar señales;
note left
    Es útil para filtrar errores
    en los sensores de Hall que
    reportan las velocidades angulares
    en las ruedas.
end note
:calcular valor porcentual\nde la velocidad;
if(la diferencia, en valores porcentuales,\nentre la velocidad y la potencia supera\nal valor máximo configurado?) then (SI)
    #Tomato:se genera una alerta de\nseguridad con criticidad\nalta indicando el peligro;
else (NO)
    #LightGreen:se genera un alerta de seguridadd\nindicando que las velocidades y las\npotencias están bajo los parámetros\nde consistencia establecidos;
endif
:se envía el alerta generada mediante\nun callback al componente Dm3Security\npara que procese la información y tome\nlas acciones correspondientes;
:esperar 100ms;
endwhile
stop

@enduml

' SVG URL: ![Diagrama_de_flujo_Dm3Security_Pows](http://www.plantuml.com/plantuml/svg/TLJ1RXCn4BtxAqRYqaeLAkAM742qG95egLJ4AL8qiMTJjzwPCFQcH8YFwGTmGDouviSOEsdJYhA7R6oFttipRsPVvu9QXZx1SSIvOe_JGDCk3LSoFUvVNf0VD9RLz5nkiilNaHTeGO2-nANjmtS7zhn1VprN6JWSIHA5qyZbI0dxpQbe8DsSd9CERVETS3d3dk0BQK16z-C1F4kX_q2V2DFgc6wU1dcIpf1hacxKNb0kJLaOkvlBc6Yl_KBHWVQT6yci49E2qaBKD0I2XMbX7p5FU0LBIk9Zm43Pph8TdqeHFPKm91gxKHTJKLJ8jFw5YVBOjLGITQLfUvjX_QV413LFk8icLL7ABO8OacG3u5ptge8JJ0c-3jJEDyhGeZ0_aeCy7n8-XB40IojWVkw8Gokg6tbCliR14ck13CmJbm7JX8qguGvpx6AtPniXTgIj10SLjjqpljrDoWSJjh_w-3wiwlAkV9271IbE6DEMkb_VVekzW1VkudnG3F9gtzmnZhsB3_ijZMUVfSSYeqmmhyOW38nWb5O2Ays4CzdDncOmuArNOoElF1OIEKIF70J8QaufMYkD7IN3splxjENu6EUNvRqIyIEU7GtSinZk3j8i-SU5chDrodtJ0EMolcMOuPKqOytuzMrFHIMtYfli7FEsHXQCiqG69jOwPbhiNDL4l5p_n9h3LjD6P43eAKJaOfKmmUPjcjcyM9JXzWkfhX0ycED96x2cVA7YAJVB8dUYFVgu_isMGP7Uy6fcw7qqa6neQfuRO8WLqiIDR4crULyS7lORiMsKRDPauTnhMzjNvIy0 "Diagrama_de_flujo_Dm3Security_Pows")